# Generated by Django 5.0 on 2024-06-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('WORKER', 'Worker'), ('MANAGER', 'Manager')], default='WORKER', max_length=20),
        ),
    ]
