# Generated by Django 5.0 on 2024-06-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='qr_code',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
