# Generated by Django 5.0 on 2024-06-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='qr_code',
        ),
    ]
